version: '3.9'

services:
  server:
    platform: linux/amd64
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
  frontend:
    platform: linux/amd64
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
     - server   
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - URI=http://localhost:5000